In [52]:
import numpy as np
import pandas as pd
import sklearn
import pickle


In [53]:
df=pd.read_csv("Churn_Modelling.csv")

In [54]:
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0


In [55]:
## Data Preprocessing

df=df.drop(["RowNumber","CustomerId","Surname"],axis=1)

In [56]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1


In [57]:
## Label Encoding for categorical variables

In [58]:
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder

In [59]:

geo_encoder = OneHotEncoder(sparse=False)
geo_encoding = geo_encoder.fit_transform(df[['Geography']])

geo_df = pd.DataFrame(
    geo_encoding,
    columns=geo_encoder.get_feature_names_out(['Geography'])
)


In [60]:
geo_df.head(2)

,Geography_France,Geography_Germany,Geography_Spain
0,1.0,0.0,0.0
1,0.0,0.0,1.0


In [61]:
df = pd.concat([df, geo_df], axis=1)


In [62]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0


In [63]:
# Label encode
gender_encoding = LabelEncoder()
df['Gender'] = gender_encoding.fit_transform(df['Gender'])  # 1D array



In [64]:
df = df.drop(columns={'Geography'})

In [65]:
df.head(5)

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0


In [ ]:
'CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts',
       'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Geography_France',
       'Geography_Germany', 'Geography_Spain'

In [66]:
df.columns

Index(['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts',
       'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited',
       'Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype='object')

In [67]:
# Save Encoding files as pickle:

with open('geo_encoder.pkl','wb') as file:
    pickle.dump(geo_encoder,file)
with open('gender_encoding.pkl','wb') as file:
    pickle.dump(gender_encoding,file)    

In [68]:
#SPlit data in train test

X=df.drop('Exited',axis=1)
y=df['Exited']

In [89]:
X

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,0.0,1.0,0.0


In [69]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [70]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

why??
Imagine normalizing student test scores:

You calculate the class average (mean) and spread (std) from students who attended the class (train).

Then you use that average to score new incoming students (test).

You don’t adjust the average just because new students came in — that would bias your evaluation.

In [71]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [85]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [87]:
X_test.size

24000

In [73]:

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [74]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime


In [90]:
(X_train.shape[1],)

(12,)

In [103]:
# Build ANN model
model=Sequential(
[ Dense(64,activation='relu',input_shape=(12,)),#HL1 connected with input layer
  Dense(32,activation='relu'),#HL2 
  Dense(1,activation='sigmoid')#o/p
])

In [104]:
 model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 64)                832       
                                                                 
 dense_13 (Dense)            (None, 32)                2080      
                                                                 
 dense_14 (Dense)            (None, 1)                 33        
                                                                 
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [105]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [106]:
# Compile the model
model.compile(
    optimizer=opt,
    loss='binary_crossentropy',
    metrics=['accuracy']  # <-- should be 'metrics' (plural)
)


In [107]:
# Setup the tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
log_dir="logs/fit"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [108]:
 ## Setup early stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',
                                      patience=10,restore_best_weights=True)

In [109]:
#Train the model
history=model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=100,callbacks=[tensorflow_callback,early_stopping_callback]
                 )

Epoch 1/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3939 - accuracy: 0.8355 - val_loss: 0.3752 - val_accuracy: 0.8410
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3517 - accuracy: 0.8558 - val_loss: 0.3422 - val_accuracy: 0.8615
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3474 - accuracy: 0.8575 - val_loss: 0.3616 - val_accuracy: 0.8555
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3403 - accuracy: 0.8614 - val_loss: 0.3557 - val_accuracy: 0.8495
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3429 - accuracy: 0.8610 - val_loss: 0.3479 - val_accuracy: 0.8605
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3376 - accuracy: 0.8616 - val_loss: 0.3453 - val_accuracy: 0.8510
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3377 - accuracy: 0.8597 - val_loss: 0.3555 - val_accuracy: 0.8550

In [110]:
model.save('model.h5')

In [111]:
X_test.shape

(2000, 12)

In [112]:
#Churning Prediction
prediction=model.predict(X_test)

63/63 [==============================] - 0s 2ms/step


In [113]:
prediction

array([[0.09035943],
       [0.02134515],
       [0.14270824],
       ...,
       [0.5485864 ],
       [0.13488309],
       [0.20925727]], dtype=float32)